### ISSUE TITLE
amule.sh aborted

### ISSUE THREAD

**Issue by cescm** [tchabaud/dockerfiles#8]
I have an error when launching the docker-compose with your image. Everything goes well except the last line, that aborts the execution of amule.sh and makes amule container to infinite loop restart: (this is the second execution, in the first the user and group are created correctly, so that now is showing they will not be created)

Group 101 already exists. Won't be created.
Group amule with GID 101 will be used as amule group.
User 1026 already exists. Won't be added.
/home/amule/.aMule/amule.conf file found. Using existing configuration.
/home/amule/.aMule/remote.conf file found. Using existing configuration.
 2019-03-24 21:32:42: Logging to stdout enabled
--== cannot generate backtrace ==--

--------------------------------------------------------------------------------
A fatal error has occurred and aMule has crashed.
Please assist us in fixing this problem by posting the backtrace below in our
'aMule Crashes' forum and include as much information as possible regarding the
circumstances of this crash. The forum is located here:
    http://forum.amule.org/index.php?board=67.0
If possible, please try to generate a real backtrace of this crash:
    http://wiki.amule.org/wiki/Backtraces

----------------------------=| BACKTRACE FOLLOWS: |=----------------------------
Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)
Running on: Linux 3.10.105 x86_64

--------------------------------------------------------------------------------
/home/amule/amule.sh: line 274:    21 Aborted                 sudo -H -u "#${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"

**Comment by t-chab** [comment]
Hi @cescm,

Sorry for the trouble. Could you please test with latest image ?

**Comment by shellus** [comment]
I have the same problem when I enable upnp
`UPnPEnabled=1`

It runs correctly when upnp is disabled

This is docker logs：
```
amule_1         | Group 33 already exists. Won't be created.
amule_1         | Group xfs with GID 33 will be used as amule group.
amule_1         | User 33 already exists. Won't be added.
amule_1         | No GUI password specified, using generated one: ITEsHPGabSyHWwDuptNc1HtPsPNdDz4GYKYUOIjol1EDCQPiuKbqeH2crP98UDBI
amule_1         | /home/amule/.aMule/amule.conf file found. Using existing configuration.
amule_1         | /home/amule/.aMule/remote.conf file found. Using existing configuration.
amule_1         | Switched web UI theme to AmuleWebUI-Reloaded
amule_1         |  2019-04-16 01:50:20: Logging to stdout enabled
amule_1         | --== cannot generate backtrace ==--
amule_1         |
amule_1         |
amule_1         | --------------------------------------------------------------------------------
amule_1         | A fatal error has occurred and aMule has crashed.
amule_1         | Please assist us in fixing this problem by posting the backtrace below in our
amule_1         | 'aMule Crashes' forum and include as much information as possible regarding the
amule_1         | circumstances of this crash. The forum is located here:
amule_1         |     http://forum.amule.org/index.php?board=67.0
amule_1         | If possible, please try to generate a real backtrace of this crash:
amule_1         |     http://wiki.amule.org/wiki/Backtraces
amule_1         |
amule_1         | ----------------------------=| BACKTRACE FOLLOWS: |=----------------------------
amule_1         | Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)
amule_1         | Running on: Linux 4.18.0-18-generic x86_64
amule_1         |
amule_1         |
amule_1         | --------------------------------------------------------------------------------
amule_1         | /home/amule/amule.sh: line 285:    23 Aborted                 (core dumped) sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"

```

**Comment by t-chab** [comment]
Hi, and thanks @shellus for the details 

I was able to reproduce the issue and opened an [issue](https://github.com/amule-project/amule/issues/161) upstream.

@cescm : do you have UPnP enabled ?

**Comment by cescm** [comment]
No, I don't have UPnP enabled, I've checked and is `UPnPEnabled=0` Here is my docker-compose:

version: '2'
services:
  amule:
      image: tchabaud/amule:latest
      container_name: amule
      ports:
        - 54711:4711
        - 54662:4662
        - 54672:4672/udp
        - 54665:4665/udp
      environment:
        - WEBUI_PWD=MyPassword
        - GUI_PWD=MyPassword
        - TZ=Europe/Madrid
        - PUID=1026
        - PGID=101
      restart: unless-stopped
      volumes:
        - /volume1/docker/amule/conf:/home/amule/.aMule
        - /volume1/DATOS/DESCARGAS/incomplete:/temp
        - /volume1/DATOS/DESCARGAS/complete:/incoming`

**Comment by LeidenSpain** [comment]
Hi,

I have the same problem with this docker:
```
docker run \
--name="amule" \
-p 4711:4711 \
-p 4662:4662 \
-p 4672:4672/udp \
-e TZ=Europe/Madrid \
-e PUID=1000 \
-e PGID=1000 \
-e WEBUI_PWD=dunkelAE \
-v /docker/amule/conf:/home/amule/.aMule \
-v /docker/amule/incoming:/incoming \
-v /docker/amule/temp:/temp \
tchabaud/amule
-e GUI_PWD=dunkelAE \
```

And happends the same error:
```
No GUI password specified, using generated one: wdMkPezTKZyGOqLGz4rPySENgp2PmA0Q5aeRf2oUOecQksfsBxBkvqzmTB1ozO51
/home/amule/.aMule/amule.conf file NOT found. Generating new default configuration ...
/home/amule/.aMule/amule.conf successfullly generated.
/home/amule/.aMule/remote.conf file NOT found. Generating new default configuration ...
/home/amule/.aMule/remote.conf successfullly generated.
Using default theme for web UI.
 2020-05-21 21:24:47: Logging to stdout enabled
--== cannot generate backtrace ==--
--------------------------------------------------------------------------------
A fatal error has occurred and aMule has crashed.
Please assist us in fixing this problem by posting the backtrace below in our
'aMule Crashes' forum and include as much information as possible regarding the
circumstances of this crash. The forum is located here:
    http://forum.amule.org/index.php?board=67.0
If possible, please try to generate a real backtrace of this crash:
    http://wiki.amule.org/wiki/Backtraces
----------------------------=| BACKTRACE FOLLOWS: |=----------------------------
Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)
Running on: Linux 5.3.0-53-generic x86_64
--------------------------------------------------------------------------------
/home/amule/amule.sh: line 285:    23 Aborted                 (core dumped) sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"
Group 1000 already exists. Won't be created.
Group amule with GID 1000 will be used as amule group.
User 1000 already exists. Won't be added.
No GUI password specified, using generated one: TruAJwtmkk6CGsRf0VYAtUXr5pE9zMsV6B2pOTYMIDFLLFHl5rLxwzm6kSFrMFgl
/home/amule/.aMule/amule.conf file found. Using existing configuration.
/home/amule/.aMule/remote.conf file found. Using existing configuration.
Using default theme for web UI.
 2020-05-21 21:27:21: Logging to stdout enabled
--== cannot generate backtrace ==--
--------------------------------------------------------------------------------
A fatal error has occurred and aMule has crashed.
Please assist us in fixing this problem by posting the backtrace below in our
'aMule Crashes' forum and include as much information as possible regarding the
circumstances of this crash. The forum is located here:
    http://forum.amule.org/index.php?board=67.0
If possible, please try to generate a real backtrace of this crash:
    http://wiki.amule.org/wiki/Backtraces
----------------------------=| BACKTRACE FOLLOWS: |=----------------------------
Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)
Running on: Linux 5.3.0-53-generic x86_64
--------------------------------------------------------------------------------
/home/amule/amule.sh: line 285:    21 Aborted                 (core dumped) sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"

```

Has anyone managed to solve this problem?
My system:
CPU: Intel N4100 / UHD600
O.S.: Lubuntu 18.04
Docker version 19.03.9, build 9d988398e7

**Comment by Sinetiqueta** [comment]
Hi guys,

The issue with the last line was solved?

`/home/amule/amule.sh: line 285:    23 Aborted                 (core dumped) sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"`

I'm doing a fresh installation on a OMV5/Portainer, and I'm not able to find the solution.

Tanks!

**Comment by t-chab** [comment]
@Sinetiqueta : sorry but this bug is still not fixed. I don't have any clue how to solve this. Sometimes disabling upnp could fix the issue according to @shellus experience.

**Comment by Sinetiqueta** [comment]
Thanks @tchabaud  for the information.
Is it easy to enable/disable? (0/1) 

Thanks again!

**Comment by t-chab** [comment]
Yes, you just have to set _UPnPEnabled_ to 0 (or 1 to enable) in your _amule.conf_ file

**Comment by Sinetiqueta** [comment]
Ok, let's try. ;)

**Comment by Sinetiqueta** [comment]
Nothing. Same issue.

More info:

Just when I run the image, I go to check the LOG, and this is the full message, maybe it is a clue to find the issue?

```
2020/08/12 12:23:03 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/12 12:23:07 server: Reverse tunnelling enabled


2020/08/12 12:23:07 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/12 12:23:07 server: Listening on 0.0.0.0:8000...


2020/08/12 12:23:07 Starting Portainer 1.24.1 on :9000


2020/08/12 12:23:07 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/12 12:23:36 http error: No administrator account found inside the database (err=Object not found inside the database) (code=404)


2020/08/12 12:23:36 http error: No administrator account found inside the database (err=Object not found inside the database) (code=404)


2020/08/12 20:36:44 http error: Invalid JWT token (err=Invalid JWT token) (code=401)


2020/08/13 09:39:25 http error: Invalid JWT token (err=Invalid JWT token) (code=401)


2020/08/14 10:11:09 http error: Invalid JWT token (err=Invalid JWT token) (code=401)


2020/08/14 17:46:34 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/14 17:46:38 Templates already registered inside the database. Skipping template import.


2020/08/14 17:46:38 server: Reverse tunnelling enabled


2020/08/14 17:46:38 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/14 17:46:38 server: Listening on 0.0.0.0:8000...


2020/08/14 17:46:38 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/14 17:46:38 Starting Portainer 1.24.1 on :9000


2020/08/14 17:52:22 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/14 17:52:26 Templates already registered inside the database. Skipping template import.


2020/08/14 17:52:26 server: Reverse tunnelling enabled


2020/08/14 17:52:26 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/14 17:52:26 server: Listening on 0.0.0.0:8000...


2020/08/14 17:52:26 Starting Portainer 1.24.1 on :9000


2020/08/14 17:52:26 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/14 17:57:10 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/14 17:57:14 Templates already registered inside the database. Skipping template import.


2020/08/14 17:57:14 server: Reverse tunnelling enabled


2020/08/14 17:57:14 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/14 17:57:14 server: Listening on 0.0.0.0:8000...


2020/08/14 17:57:14 Starting Portainer 1.24.1 on :9000


2020/08/14 17:57:14 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/14 18:05:38 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/14 18:05:42 Templates already registered inside the database. Skipping template import.


2020/08/14 18:05:42 server: Reverse tunnelling enabled


2020/08/14 18:05:42 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/14 18:05:42 server: Listening on 0.0.0.0:8000...


2020/08/14 18:05:42 Starting Portainer 1.24.1 on :9000


2020/08/14 18:05:42 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/14 18:21:23 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/14 18:21:27 Templates already registered inside the database. Skipping template import.


2020/08/14 18:21:27 server: Reverse tunnelling enabled


2020/08/14 18:21:27 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/14 18:21:27 server: Listening on 0.0.0.0:8000...


2020/08/14 18:21:27 Starting Portainer 1.24.1 on :9000


2020/08/14 18:21:27 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/16 12:24:48 Warning: the --template-file flag is deprecated and will likely be removed in a future version of Portainer.


2020/08/16 12:24:52 Templates already registered inside the database. Skipping template import.


2020/08/16 12:24:52 server: Reverse tunnelling enabled


2020/08/16 12:24:52 server: Fingerprint 0a:38:ca:a4:f7:46:91:f7:9a:00:ce:9d:35:6f:db:06


2020/08/16 12:24:52 server: Listening on 0.0.0.0:8000...


2020/08/16 12:24:52 Starting Portainer 1.24.1 on :9000


2020/08/16 12:24:52 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]


2020/08/16 14:51:45 http error: Invalid JWT token (err=Invalid JWT token) (code=401)
```

regards!

**Comment by t-chab** [comment]
It seems to be the portainer log file. Can you give me the amule container log instead please ?

**Comment by Sinetiqueta** [comment]
Here, but I think is the same info that you had before with no success.,  thanks very much for your time.

_____________________________________
--== cannot generate backtrace ==--






--------------------------------------------------------------------------------


A fatal error has occurred and aMule has crashed.


Please assist us in fixing this problem by posting the backtrace below in our


'aMule Crashes' forum and include as much information as possible regarding the


circumstances of this crash. The forum is located here:


    http://forum.amule.org/index.php?board=67.0


If possible, please try to generate a real backtrace of this crash:


    http://wiki.amule.org/wiki/Backtraces




----------------------------=| BACKTRACE FOLLOWS: |=----------------------------


Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)


Running on: Linux 5.7.0-0.bpo.2-amd64 x86_64






--------------------------------------------------------------------------------


/home/amule/amule.sh: line 285:    23 Aborted                 sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"


Group 1000 already exists. Won't be created.


Group amule with GID 1000 will be used as amule group.


User 1000 already exists. Won't be added.


No GUI password specified, using generated one: unsaOIWAvcsbmHVdwUVoc4CrQQt4THZHN1wAINYJKF1zKrxkOLnRazswT96qsVxJ


/home/amule/.aMule/amule.conf file found. Using existing configuration.


/home/amule/.aMule/remote.conf file found. Using existing configuration.


Switched web UI theme to AmuleWebUI-Reloaded


 2020-08-16 18:32:40: Logging to stdout enabled


--== cannot generate backtrace ==--






--------------------------------------------------------------------------------


A fatal error has occurred and aMule has crashed.


Please assist us in fixing this problem by posting the backtrace below in our


'aMule Crashes' forum and include as much information as possible regarding the


circumstances of this crash. The forum is located here:


    http://forum.amule.org/index.php?board=67.0


If possible, please try to generate a real backtrace of this crash:


    http://wiki.amule.org/wiki/Backtraces




----------------------------=| BACKTRACE FOLLOWS: |=----------------------------


Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)


Running on: Linux 5.7.0-0.bpo.2-amd64 x86_64






--------------------------------------------------------------------------------


/home/amule/amule.sh: line 285:    23 Aborted                 sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"


Group 1000 already exists. Won't be created.


Group amule with GID 1000 will be used as amule group.


User 1000 already exists. Won't be added.


No GUI password specified, using generated one: AhUuGuVvl5C8U0lRmL7WkxNzJXmIabWQzgsWth1e01jwEG44LZkxp9RHBxkkhCVt


/home/amule/.aMule/amule.conf file found. Using existing configuration.


/home/amule/.aMule/remote.conf file found. Using existing configuration.


Switched web UI theme to AmuleWebUI-Reloaded


 2020-08-16 18:35:57: Logging to stdout enabled


--== cannot generate backtrace ==--






--------------------------------------------------------------------------------


A fatal error has occurred and aMule has crashed.


Please assist us in fixing this problem by posting the backtrace below in our


'aMule Crashes' forum and include as much information as possible regarding the


circumstances of this crash. The forum is located here:


    http://forum.amule.org/index.php?board=67.0


If possible, please try to generate a real backtrace of this crash:


    http://wiki.amule.org/wiki/Backtraces




----------------------------=| BACKTRACE FOLLOWS: |=----------------------------


Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)


Running on: Linux 5.7.0-0.bpo.2-amd64 x86_64






--------------------------------------------------------------------------------


/home/amule/amule.sh: line 285:    23 Aborted                 sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"


Group 1000 already exists. Won't be created.


Group amule with GID 1000 will be used as amule group.


User 1000 already exists. Won't be added.


No GUI password specified, using generated one: m9PYbRj3L41D0lRtkupdAJKqYAPAJWPcLsvJxABAXfblvDt351ngiNGVHhGnSQ0r


/home/amule/.aMule/amule.conf file found. Using existing configuration.


/home/amule/.aMule/remote.conf file found. Using existing configuration.


Switched web UI theme to AmuleWebUI-Reloaded


 2020-08-16 18:36:40: Logging to stdout enabled


--== cannot generate backtrace ==--






--------------------------------------------------------------------------------


A fatal error has occurred and aMule has crashed.


Please assist us in fixing this problem by posting the backtrace below in our


'aMule Crashes' forum and include as much information as possible regarding the


circumstances of this crash. The forum is located here:


    http://forum.amule.org/index.php?board=67.0


If possible, please try to generate a real backtrace of this crash:


    http://wiki.amule.org/wiki/Backtraces




----------------------------=| BACKTRACE FOLLOWS: |=----------------------------


Current version is: aMuleD 2.3.2 compiled with wxBase(GTK2) v2.8.12 (Snapshot: rev. g5d9c1f458)


Running on: Linux 5.7.0-0.bpo.2-amd64 x86_64






--------------------------------------------------------------------------------


/home/amule/amule.sh: line 285:    25 Aborted                 sudo -H -u '#'"${AMULE_UID}" sh -c "amuled -c ${AMULE_HOME} -o"
